fancybox: true
duoshuo: #duoshuo_shortname
disqus: #disqus_shortname
google_search: true
baidu_search: #baidu_search
swiftype: #swiftype_key
tinysou: #tinysou_key
menu:
  - page: home
    directory: /
    icon: icon-home
  - page: archive
    directory: archives/
    icon: icon-archive
  - page: about
    directory: about/
    icon: icon-about
  - page: rss
    directory: atom.xml
    icon: icon-rss
links:
  - title: site-name1
    url: http://www.example1.com/
  - title: site-name2
    url: http://www.example2.com/
  - title: site-name3
    url: http://www.example3.com/
